# Generated by Django 4.1.6 on 2023-05-01 18:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_banner_area'),
    ]

    operations = [
        migrations.DeleteModel(
            name='banner_area',
        ),
    ]
