# Generated by Django 4.2 on 2023-05-13 04:47

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_product_section_product_image_product_section_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='slug',
            field=models.SlugField(blank=True, default='', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='product',
            name='featured_Image',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_Information',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='product_image',
            name='image_url',
            field=models.CharField(max_length=500),
        ),
    ]
